from service_api.schemas.register_schema import RegisterSchema
from service_api.schemas.login_schema import LoginSchema
from service_api.schemas.petition_schema import PetitionPostSchema
from service_api.schemas.petition_schema import PetitionPutSchema
